### ISSUE TITLE
Content Streching

### ISSUE THREAD

**Issue by JoshuaYoungDesign** [dannymcclain/fit-to-parent#1]
Would it be possible to make it not stretch the selected content when Constrain Proportions is active
and could you add more fill types similar to how shape image fill works - fill image, fit image, etc.

<img width="2560" alt="Screen Shot 2020-09-29 at 2 01 20 pm" src="https://user-images.githubusercontent.com/44690738/94511347-63d3be00-025c-11eb-826c-18bc13228df8.png">

**Comment by dannymcclain** [comment]
Hey Joshua, I'm no longer working on/maintaining this plugin. Feel free to fork the repo and make those modifications though!
